# app/scenarios/service.py

from uuid import UUID
from typing import List
from fastapi import HTTPException

from .schemas import (
    ScenarioCreate,
    ScenarioUpdate,
    ScenarioRead,
    ScenarioSummary,
    RonetParameters
)
from . import repository as repo

def get_or_create_baseline(project_id: UUID, user_id: str) -> ScenarioRead:
    """
    Fetch the baseline scenario. If none exists, create a default one.
    This ensures the 'Config' page always has something to load.
    """
    row = repo.get_baseline_scenario(project_id, user_id)
    
    if row:
        return ScenarioRead(**row)
    
    # Create default baseline if missing
    # We explicitly initialize default parameters here
    default_payload = ScenarioCreate(
        name="Baseline Scenario",
        description="Default configuration generated by system.",
        is_baseline=True,
        parameters=RonetParameters() 
    )
    
    # Create it
    new_row = repo.create_scenario(
        project_id, 
        user_id, 
        default_payload.model_dump()
    )
    return ScenarioRead(**new_row)

def update_scenario(
    project_id: UUID,
    scenario_id: UUID,
    user_id: str,
    payload: ScenarioUpdate,
) -> ScenarioRead:
    # Exclude unset to allow partial updates (PATCH behavior)
    data = payload.model_dump(exclude_unset=True)
    
    row = repo.update_scenario(project_id, scenario_id, user_id, data)
    if not row:
        raise HTTPException(status_code=404, detail="Scenario not found.")
    return ScenarioRead(**row)

def list_scenarios(project_id: UUID, user_id: str) -> List[ScenarioSummary]:
    rows = repo.list_scenarios(project_id, user_id)
    return [ScenarioSummary(**row) for row in rows]

def get_scenario(project_id: UUID, scenario_id: UUID, user_id: str) -> ScenarioRead:
    row = repo.get_scenario(project_id, scenario_id, user_id)
    if not row:
        raise HTTPException(status_code=404, detail="Scenario not found.")
    return ScenarioRead(**row)